# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.geekzl.com
# date_format: "ordinal"
title:  极客中心
subtitle: 致力于分享实用技术，也谈赚钱思维.
alias: 极客中心页
description: "极客中心博客，专注于分享IT前沿技术、干货知识、热点资讯等，同时分享硬核的自媒体赚钱方法、推广技巧和运营实战."
keywords: 极客中心页, 极客中心, Python, 极客, VR
encoding: "utf-8"
side_bar_repo_limit: 5
repository: wpfgeek/wpfgeek.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true

# 组件配置
components:
    # 分享
    share:
        enabled: true
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-10-15
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: 极客社区
organization: 
organization_url: 
github_username: wpfgeek
location: Shanghai, China
email: legege007@yeah.net

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

  -
    href: /sitemap.xml
    label: 站点地图

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
highlighter: rouge
paginate: 10

# lsi: true

quiet: false
excerpt_separator: "\n\n"
permalink: :title.html
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
    - jekyll-redirect-from
#     - jekyll-mentions

# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/ 
  wiki:
      output: true
      permalink: /wiki/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
    values:
      image: https://pic.rmb.bdstatic.com/bjh/580403fac4c45b5e0d04a27c89bc1194.jpeg

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wpfgeek
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wpfgeek
    repo: geekzl.com
    oauth:
        client_id: 5c65f5ba06d7264fbcf2
        client_secret: fc67852d30cb77148093c699b75cb156f34c02bc
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wpfgeek
    repo: geekzl.com
    clientID: 5c65f5ba06d7264fbcf2  # owner: by8
    clientSecret: fc67852d30cb77148093c699b75cb156f34c02bc

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

exclude:
- [vendor]

# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
#     adsense:
#         footer: true
#         sidebar: true 
#         content_header: true
#         content_footer: false

google_analytics_id: UA-180731079-1
baidu-analysis-id: 8b9dd7612bcef258b22a53f34dbc1ef1

# timezone: Asia/Shanghai +08:00
